# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/trading_pair.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages/trading_pair.proto',
  package='trading.messages',
  syntax='proto3',
  serialized_pb=_b('\n\x1bmessages/trading_pair.proto\x12\x10trading.messages\"<\n\x0bTradingPair\x12\x15\n\rbase_currency\x18\x01 \x01(\t\x12\x16\n\x0equote_currency\x18\x02 \x01(\tb\x06proto3')
)




_TRADINGPAIR = _descriptor.Descriptor(
  name='TradingPair',
  full_name='trading.messages.TradingPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_currency', full_name='trading.messages.TradingPair.base_currency', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quote_currency', full_name='trading.messages.TradingPair.quote_currency', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['TradingPair'] = _TRADINGPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradingPair = _reflection.GeneratedProtocolMessageType('TradingPair', (_message.Message,), dict(
  DESCRIPTOR = _TRADINGPAIR,
  __module__ = 'messages.trading_pair_pb2'
  # @@protoc_insertion_point(class_scope:trading.messages.TradingPair)
  ))
_sym_db.RegisterMessage(TradingPair)


# @@protoc_insertion_point(module_scope)
